name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v4

      - name: NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
