name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Dummy Build
        run: |
          mkdir dist
          echo "Hello, GitHub Pages!" > dist/index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
